dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
  - OpenZeppelin/openzeppelin-contracts@3.4.0
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0"
dotenv: .env
networks:
  default: development
  development:
    keyhash: "0x474e34a077df58807dbe9c96d3c009b23b3c6d0cce433e59bbf5b34f823bc56c"
    fee: 5000000000000000

  sepolia:
    vrf_coordinator: "0x8103B0A8A00be2DDC778e6e7eaa21791Cd364625"
    eth_usd_price_feed: "0x694AA1769357215DE4FAC081bf1f309aDC325306"
    link_token: "0x779877A7B0D9E8603169DdbD7836e478b4624789"
    keyhash: "0x474e34a077df58807dbe9c96d3c009b23b3c6d0cce433e59bbf5b34f823bc56c"
    fee: 5000000000000000
    verify: True
  mainnet-fork:
    eth_usd_price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}
